### ISSUE TITLE
W3C CSS Validator for todo-bootstrap running to 300+ error

### ISSUE THREAD

**Issue by arunanto** [todc/todc-bootstrap#152]
I started noticing lately that the project website in itself has 300+ css validation errors. 

http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Ftodc.github.io%2Ftodc-bootstrap%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

What could be the issues using the todo custom css style-sheet in any project?

**Comment by acmetech** [comment]
Closing this since Version 4.2 alpha validates without errors or warnings.

http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ftodc.github.io%2Ftodc-bootstrap%2Fdocs%2F4.2&profile=css3svg&usermedium=all&warning=2&vextwarning=&lang=en
