### ISSUE TITLE
equal-height-columns on col-xs

### ISSUE THREAD

**Issue by Showcase-Joz** [todc/todc-bootstrap#167]
i've noticed that the equal-height-columns snippet doesn't respond on col-xs-##

**Comment by acmetech** [comment]
Hi @Showcase-Joz,

* Does it work correctly when using Bootstrap without todc-bootstrap?
* What version of todc-bootstrap are you using?

Thanks

**Comment by Showcase-Joz** [comment]
sorry, not using todc bs

i simply put display:block; for my breakpoints below sm

**Comment by acmetech** [comment]
If you're not using todc-bootstrap, then the issue was opened in the wrong repository.
