### ISSUE TITLE
Can provide a small panel header style ?

### ISSUE THREAD

**Issue by jewway** [todc/todc-bootstrap#168]
Bootstrap preset panel header does not look good and it is  too big , if you can provide a style more like Google ?

**Comment by acmetech** [comment]
Hi @jewway,

Please provide me with a link to a Google panel header and I will take a look. 

Thanks

**Comment by jewway** [comment]
Hi @acmetech,

Maybe you can refer to the following

1.Google+ setting UI
![2015-01-10_002250](https://cloud.githubusercontent.com/assets/3501899/5683048/b724411e-985f-11e4-9066-ce3d9c7cb787.png)

2.Google Hangouts dialog
![2015-01-10_002646](https://cloud.githubusercontent.com/assets/3501899/5683060/dfa2755c-985f-11e4-8973-43867a6a7c70.png)

3.Google Gmail
![2015-01-10_002729](https://cloud.githubusercontent.com/assets/3501899/5683073/ff5c1074-985f-11e4-9a8b-64ea7fed5dcd.png)

Thank you !!

**Comment by acmetech** [comment]
@jewway,

Those examples are for modals, not panels. See http://todc.github.io/todc-bootstrap/javascript/#modals.

From the readme:

> This is a Google-styled theme for Bootstrap. Because I'm a fan of the new Google UI seen in Gmail, Docs, Calendar, etc, I decided to reproduce the look of these new UI elements for my own personal use. The project's goal isn't UI parity with Google Apps -- it's feature parity with Bootstrap, themed with Google's UI in mind.

Also see this comment: https://github.com/todc/todc-bootstrap/issues/133#issuecomment-31431365

We wont be changing the height of the modal header at this time. You can change it in your copy by modifying the modal-header class.

Thanks
