### ISSUE TITLE
Could not figured out difference between navbar and masthead

### ISSUE THREAD

**Issue by fazliddin** [todc/todc-bootstrap#171]
Is there any potential difference?
Navbar looks differently from that of bootstrap's orginal, masthead looks like navbar.

**Comment by acmetech** [comment]
The masthead is similar to the Bootstrap navbar as are the toolbar and todc-bootstrap navbar. All of these todc-bootstrap components are based off of the Bootstrap navbar. Some of the differences are height, link style, padding, margins. The todc-bootstrap components are styled to match similar components in the Google UI in Gmail, Docs, Calendar, etc.

Keep in mind that todc-bootstrap is a Google-styled theme for Bootstrap.

**Comment by fazliddin** [comment]
Thank you! I got it. Great job!

**Comment by acmetech** [comment]
You're welcome. Thanks
