### ISSUE TITLE
Indeterminate mark of checkbox is not displayed because of `-webkit-appearance: none`

### ISSUE THREAD

**Issue by kazup0n** [todc/todc-bootstrap#173]
[Specifying `-webkit-appearance: none`](https://github.com/todc/todc-bootstrap/blob/master/less/forms.less#L170) to checkbox makes the indeterminate marks invisible.

Here's my reproducing code: https://jsfiddle.net/kauzp0n/fL7fe5gL/

Is this an _as designed_ effect ?

**Comment by acmetech** [comment]
Hi @kazup0n,

Thanks for reporting this issues. This is currently as designed. Indeterminate will be supported in v4. I will look into adding support for this to v3.

**Comment by kazup0n** [comment]
@acmetech 
Thanks for the answer.
I understood that and waiting for v4 .

**Comment by kazup0n** [comment]
👍
