### ISSUE TITLE
navbar-masthead drop down issue

### ISSUE THREAD

**Issue by nwaweru** [todc/todc-bootstrap#175]
Hi,

I am trying to work with the navbar-masthead and drop downs, but I keep getting an error "Uncaught Error: Syntax error, unrecognized expression: #".

I have even started a fresh project and copy-pasted the code as is from https://todc.github.io/todc-bootstrap/components/#navbar-masthead but same error every time.

I am using todc-bootstrap v 3.0.2.

Kindly assist.

Thanks.

**Comment by todc** [comment]
Hi @nwaweru ,

If you have a JSFiddle link or a github repo demonstrating the problem, I'd be happy to take a look. Otherwise it's hard to tell what the issue is from your description.

**Comment by nwaweru** [comment]
HI @todc ,

It works fine on https://jsfiddle.net/nwaweru/7pLdzubm/7/, but I am still unable to get the dropdown working on my local project.

Same setup, but I am using bower to install todc-bootstrap and using the bootstrap files within the framework as opposed to loading from CDNs and the likes.

I will further troubleshoot and see what issue could be.

I can close this now and thanks for the quick response.
