### ISSUE TITLE
[.btn:not(.btn-link)] sholud never have Webkit's default outline

### ISSUE THREAD

**Issue by zcyzcy88** [todc/todc-bootstrap#176]
https://todc.github.io/todc-bootstrap/css#buttons-options

### Chrome (may any browser)

1. Click and **hold** a `.btn.btn-default` button
2. Look the outline
><img width="162" alt="2017-03-22 19_06_03-css todc bootstrap" src="https://cloud.githubusercontent.com/assets/15178410/24195077/564f0e4e-0f33-11e7-9ea7-a204b4d48dfc.png">

### or

1. Click a `.btn:not(.btn-default):not(.btn-link)` button
2. Look the outline
><img width="164" alt="2017-03-22 18_47_16-css todc bootstrap" src="https://cloud.githubusercontent.com/assets/15178410/24195079/57f6c098-0f33-11e7-9e09-7eedbc9a7d9c.png">

**Comment by acmetech** [comment]
Hi @zcyzcy88,

Does this issue also occur in Bootstrap 3 and/or 4 or is it specific to todc-bootstrap?

Thanks

**Comment by zcyzcy88** [comment]
TWBS 3 don't implement its own outline style, and don't Webkit's default outline
<img width="79" alt="2017-03-22 21_42_41-css bootstrap" src="https://cloud.githubusercontent.com/assets/15178410/24200591/83e6d322-0f48-11e7-9b94-bf77498c7f54.png">

TWBS 4 implemented its own outline style, and removed Webkit's default outline
<img width="115" alt="2017-03-22 21_45_24-buttons bootstrap" src="https://cloud.githubusercontent.com/assets/15178410/24200938/9555a902-0f49-11e7-9406-73848dc9e221.png">

TODC implemented its own outline style, and partially removed Webkit's default outline
