### ISSUE TITLE
Should no :focus outline when :active

### ISSUE THREAD

**Issue by zcyzcy88** [todc/todc-bootstrap#179]
Note:
Browser add `focus` and `active` status when you ~~~_mouseup_~~~ mousedown a element

---

### Now
https://todc.github.io/todc-bootstrap/css/#buttons-options
<img width="119" alt="2017-03-27 19_40_41-css todc bootstrap" src="https://cloud.githubusercontent.com/assets/15178410/24356407/68ccb768-132c-11e7-91e8-7aa344759a83.png">

---

### Expect
https://translate.google.com
<img width="124" alt="2017-03-27 19_41_32-google translate" src="https://cloud.githubusercontent.com/assets/15178410/24356417/7225377c-132c-11e7-8510-faff171c1ef0.png">

**Comment by acmetech** [comment]
Hi @zcyzcy88,

What version(s) of what browser(s) are you seeing this in?

Thanks

**Comment by zcyzcy88** [comment]
All.

Click and hold a colored button.
The outline should not appear when holding.

**Comment by acmetech** [comment]
@zcyzcy88,

I understand, but what browser(s)/version(s) are you seeing this in?

Thanks

**Comment by zcyzcy88** [comment]
Windows 10 desktop:
- IE 11
- Chrome 59 (Canary)
- Firefox 52

**Comment by acmetech** [comment]
I am unable to replicate this with Firefox 52.0.1 on a Mac at https://translate.google.com. However, I can replicate it with Firefox 52.0.1 at Gmail. I can also replicate it using Chrome 57.0.2987.110 at  https://translate.google.com.

Thanks

**Comment by zcyzcy88** [comment]
This issue is a visual improvement, I think outline should not cover inner shadow.

Thanks for your continue fixing.

**Comment by acmetech** [comment]
You're welcome
