### ISSUE TITLE
Dependabot dependency management

### ISSUE THREAD

**Issue by acmetech** [todc/todc-bootstrap#188]
Hi @todc,

Would you please install the [Dependabot Preview](https://github.com/apps/dependabot-preview/installations/new/) when you have a chance.

Thanks

**Comment by todc** [comment]
Should be all set now. Let me know if you need anything else.

**Comment by acmetech** [comment]
Thank you

**Comment by acmetech** [comment]
I'm not seeing any pull requests from Dependabot. Please confirm the Dependabot configuration in the [dashboard](https://app.dependabot.com/auth/sign-in). Apparently adding the .dependabot/config.yml is not enough.

todc-bootstrap > ‎/package.json‎
Language: Javascript
Update schedule: Weekly updates
Directory: /
Reviewers: acmetech
Labels: dependencies, v5

**Comment by todc** [comment]
Ok, should be good now. I can see a few pull requests, so hopefully that's a good sign.

**Comment by acmetech** [comment]
Great, thanks.
