### ISSUE TITLE
Default branch name

### ISSUE THREAD

**Issue by acmetech** [todc/todc-bootstrap#431]
Hi @todc,

What are your thoughts on renaming the "master" branch to "main"? Bootstrap did it here [c28934cb1871d6b6bd6a866660493a1137de17c6](https://github.com/twbs/bootstrap/commit/c28934cb1871d6b6bd6a866660493a1137de17c6).

If you would like to change the name, I don't have access to the repository settings to change the default branch. I can take care of everything else and then the default can be changed.

Thanks

**Comment by todc** [comment]
What's the reason for changing the default branch to `main`?

I can make the change if you want. Just need to push the new branch to github first so I can switch it over.

**Comment by acmetech** [comment]
I'm trying to minimize the number of differences between bootstrap and todc-bootstrap. This way the fewest number of configuration, build and, documentation files need to be change when bootstrap is updated.

I don't know if this is the reason that bootstrap changed things, but these changes are being made/requested on other repositories as well. 

Scott Hanselman wrote: 

> The Internet Engineering Task Force (IETF) points out that "Master-slave is an oppressive metaphor that will and should never become fully detached from history" as well as "In addition to being inappropriate and arcane, the master-slave metaphor is both technically and historically inaccurate." There's lots of more accurate options depending on context and it costs me nothing to change my vocabulary, especially if it is one less little speed bump to getting a new person excited about tech.

**Comment by todc** [comment]
Cool, thanks for the explanation. Happy to make `main` the default branch. There's no "rename" in settings, so just push a `main` branch to github and I'll make it the default.

**Comment by acmetech** [comment]
You're welcome. I've pushed main. Thanks.

**Comment by todc** [comment]
Thanks, `main` is now the default branch.

**Comment by acmetech** [comment]
Thank you. `master` has been deleted
