### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by acmetech** [todc/todc-bootstrap#432]
Hi @todc,

Bootstrap has changed its logo for version 5.
![bootstrap-logo-shadow](https://user-images.githubusercontent.com/134294/85163536-f6fa6200-b230-11ea-9cb4-2fc11744aadf.png)

I've updated the todc-bootstrap logo to reflect the new design. Let me know your thoughts.
![todc-bootstrap-logo](https://user-images.githubusercontent.com/134294/85163587-0e394f80-b231-11ea-96b7-acd2244d9588.png)

Thanks

**Comment by esilva88** [comment]
I think this looks fine, these could be extra considerations:

- "TODC" uppercased to maximize impact 
- Visibility when icon is smaller
- Padding to the left seems to be a bit narrower than right

**Comment by todc** [comment]
👍

**Comment by acmetech** [comment]
@esilva88,

Thank you for your feedback. 

- The reason that todc is lowercase is to match the owners nickname
- I will look into this
- You are correct and I will adjust this

I did notice the gradient and it was a conscious decision to remove it. The logo was based on Google's buttons, which do not tend to have gradients.

**Comment by acmetech** [comment]
@todc,

Thanks. I will make some adjustments and push the changes.

**Comment by acmetech** [comment]
Updated logo.

![todc-bootstrap-logo-shadow](https://user-images.githubusercontent.com/134294/85215182-f5b95a00-b342-11ea-9fc4-92c7ab7d65fb.png)
